name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

# https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
# https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      ARTIFACTS_PATH: ${{ github.workspace }}/artifacts

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.202
    - name: Experimental action
#      if: startsWith(github.ref, '<skip>refs/tags/')
#      run: |
#        echo ${{ github.ref }}
#        echo ${{ github.sha }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --nologo -p:VersionSuffix=ci${{ github.run_number }}
    - name: Test
      run: dotnet test --configuration Release --no-build --no-restore --nologo --verbosity normal -p:VersionSuffix=ci${{ github.run_number }}
    - name: Pack
      run: dotnet pack --configuration Release --no-build --no-restore --nologo --output ${{ env.ARTIFACTS_PATH }} -p:VersionSuffix=ci${{ github.run_number }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts-${{ github.run_number }}-${{ github.sha }}
        path: ${{ env.ARTIFACTS_PATH }}
#    - name: Add GitHub NuGet feed source
#      run: dotnet nuget add source https://nuget.pkg.github.com/neliva/index.json --name GitHub --username neliva --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
#    - name: Push to GitHub NuGet feed
#      run: dotnet nuget push *.nupkg --source GitHub --timeout 120 --disable-buffering true
#      working-directory: ./artifacts